---
name: Build
run-name: Build triggered by @${{ github.actor }}

on:
  pull_request:
    paths:
      - 'src/**'
      - 'static/**'
      - 'bun.lock'
      - 'package.json'
      - 'tsconfig.json'
      - 'svelte.config.js'
      - 'vite.config.js'
      - 'jsconfig.json'
    branches:
      - main
    types: ['opened', 'synchronize', 'reopened']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent build,
# skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want
# to allow these production deployments to complete.
concurrency:
  group: 'build'
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: linux-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            linux-bun-${{ hashFiles('**/bun.lock') }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Create Website
        run: bun run build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'
