---
name: Lint
run-name: Lint triggered by @${{ github.actor }}

on:
  pull_request:
    paths:
      - 'src/**'
      - '.eslintrc.cjs'
      - '.eslintignore'
      - '.prettierignore'
      - '.prettierrc'
    branches:
      - main
    types: ['opened', 'synchronize', 'reopened']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: linux-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            linux-bun-${{ hashFiles('**/bun.lock') }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint
